# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build react app
      run: |
        npm ci
        npm run build
      shell: bash
    - name: Deploy to server
      run: |
        # SCP build directory to ubuntu server
        scp -o StrictHostKeyChecking=no -r ./dist/* ubuntu@44.202.40.105:/var/www/salon
        # SSH to ubuntu server and restart nginx
        ssh -o StrictHostKeyChecking=no ubuntu@44.202.40.105 'bash -s' < sudo systemctl restart nginx
      shell: bash
      